In [ ]:
import numpy as np

Array 1D :  [0 1 2 3 4 5 6 7 8 9]
Array 1D :  [3.14 2.17 0.   1.   2.  ]
Type de données :  float64


## Exercice 1

In [ ]:
array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Array 1D : ", array_1d)

## Exercice 2

In [ ]:
my_array = np.array([3.14, 2.17, 0, 1, 2])
print("Array 1D : ", my_array)
print("Type de données : ", my_array.dtype)

Array 1D :  [3.14 2.17 0.   1.   2.  ]
Type de données :  float64


## Exercice 3

In [ ]:
my_array_3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
print("Array 3D : ", my_array_3)

Array 3D :  [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercice 4

In [ ]:
rng = np.random.default_rng()
my_array_4 = rng.random((4, 5))
print("Array 4D : ", my_array_4)

Array 4D :  [[0.26161213 0.29849114 0.81422574 0.09191594 0.60010053]
 [0.72856053 0.18790107 0.05514663 0.27496937 0.65743301]
 [0.56226566 0.15006226 0.43263079 0.6692973  0.42278467]
 [0.6331844  0.96743595 0.68306482 0.39162483 0.18725257]]


## Exercice 5

In [ ]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print("Array 2D : ", array[2, :])

Array 2D :  [21 22 23 22 22]


## Exercice 6

In [ ]:
array_1 = np.arange(10)
array_1 = np.random.permutation(array_1) 
print("Array 1D : ", array_1)

Array 1D :  [4 1 6 0 7 5 8 9 2 3]


## Exercice 7

In [ ]:
array_3d = np.eye(4)
print("Array 3D : ", array_3d)

Array 3D :  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Exercice 8

In [ ]:
array_8 = np.arange(2, 10)

sum_array_8 = np.sum(array_8)
print("Somme des éléments de array_8 : ", sum_array_8)

average_array_8 = np.mean(array_8)
print("Moyenne des éléments de array_8 : ", average_array_8)

Somme des éléments de array_8 :  44
Moyenne des éléments de array_8 :  5.5


## Exercice 9

In [ ]:
array_9 = np.arange(1, 21)
print("Array 1D : ", array_9)
array_9_reshaped = array_9.reshape(4, 5)
print("Array 2D : ", array_9_reshaped)

Array 1D :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Array 2D :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Exercice 10

In [ ]:
array_10 = np.arange(10)
print("Array 1D : ", array_10)
odd_numbers = array_10[array_10 % 2 == 1]
print("Nombres impairs : ", odd_numbers)

Array 1D :  [0 1 2 3 4 5 6 7 8 9]
Nombres impairs :  [1 3 5 7 9]
